### ISSUE TITLE
codemetrics-cli reports different results than  codemetrics VSCode extension

### ISSUE THREAD

**Issue by kopach** [kisstkondoros/codemetrics-cli#8]
When I run `codemetrics-cli` against my project files, I get different results then when using VSCode extension.
For example, in VSCode I have Complexity Level High set to `10` (default value). When I run codemetrics-cli like this: `codemetrics-cli --pattern 'src/**/!(*test|*mock|*stories).{ts,tsx}' --threshold 11`, I'm getting a report for files where VSCode doesn't show any complexity above `10` (High level)

**Comment by kisstkondoros** [comment]
The options have a different meaning:
"codemetrics.basics.ComplexityLevelHigh" -> is this complexity something which should be considered complex?
"codemetrics.basics.CodeLensHiddenUnder" -> hide unrelevant pieces below this, roughly the same as threshold

I can imagine some things are not being shown in case of the vscode extension...
Could you provided some examples?

**Comment by kopach** [comment]
hi @kisstkondoros, thanks for your response. I can't much show my code, so tried to run `codemetrics-cli` against public projects to find a similar issue.
So, when I run `npx codemetrics-cli --pattern 'src/**/!(*test|*mock|*stories|serviceWorker).tsx' --lint --threshold 11` against this project: https://github.com/kopach/ag-grid/tree/latest/community-modules/react – I'm getting code complexity number **118** for this file https://github.com/kopach/ag-grid/blob/latest/community-modules/react/src/next/cellComp.tsx, but VSCode extension shows at maximum number **78**
<img width="425" alt="image" src="https://user-images.githubusercontent.com/8749624/125414578-473ea279-1705-40dd-b23b-bc005a1ead4b.png">

I'm guessing, that `codemetrics-cli` is showing complexity of entire file (it sums complexities of each top level function per file) while VSCode extension shows complexity per function.

If my guess is correct, is there any way I can configure/update `codemetrics-cli` to show complexity per top level function in file instead of per file?

**Comment by kopach** [comment]
@kisstkondoros, I think, I've found the solution I was looking for. Please, check this PR: https://github.com/kisstkondoros/codemetrics-cli/pull/12
